// Mocks generated by Mockito 5.4.6 from annotations
// in sam_pro/test/admin/attendance/screens/admin_attendance_report_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:sam_pro/Admin/Attendance/models/student_attendance_summary.dart'
    as _i2;
import 'package:sam_pro/Admin/Attendance/services/admin_attendance_service.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeStudentAttendanceSummary_0 extends _i1.SmartFake
    implements _i2.StudentAttendanceSummary {
  _FakeStudentAttendanceSummary_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AdminAttendanceService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAdminAttendanceService extends _i1.Mock
    implements _i3.AdminAttendanceService {
  MockAdminAttendanceService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<String>> fetchCourseNames(
    String? semester,
    String? branch,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchCourseNames,
          [
            semester,
            branch,
          ],
        ),
        returnValue: _i4.Future<List<String>>.value(<String>[]),
      ) as _i4.Future<List<String>>);

  @override
  _i4.Future<List<String>> fetchStudentIds(
    String? semester,
    String? branch,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchStudentIds,
          [
            semester,
            branch,
          ],
        ),
        returnValue: _i4.Future<List<String>>.value(<String>[]),
      ) as _i4.Future<List<String>>);

  @override
  _i4.Future<_i2.StudentAttendanceSummary> computeStudentSummary(
    String? studentId,
    String? semester,
    List<String>? courseNames,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #computeStudentSummary,
          [
            studentId,
            semester,
            courseNames,
          ],
        ),
        returnValue: _i4.Future<_i2.StudentAttendanceSummary>.value(
            _FakeStudentAttendanceSummary_0(
          this,
          Invocation.method(
            #computeStudentSummary,
            [
              studentId,
              semester,
              courseNames,
            ],
          ),
        )),
      ) as _i4.Future<_i2.StudentAttendanceSummary>);

  @override
  _i4.Future<List<_i2.StudentAttendanceSummary>> generateReport(
    String? semester,
    String? branch,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateReport,
          [
            semester,
            branch,
          ],
        ),
        returnValue: _i4.Future<List<_i2.StudentAttendanceSummary>>.value(
            <_i2.StudentAttendanceSummary>[]),
      ) as _i4.Future<List<_i2.StudentAttendanceSummary>>);
}
